ALTER TABLE "stores"
ADD COLUMN IF NOT EXISTS "pettyCashBalance" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "stores"
ADD COLUMN IF NOT EXISTS "virtualCardNumber" TEXT DEFAULT '4232 4532 7654 8901';

ALTER TABLE "petty_cash_requests"
ADD COLUMN IF NOT EXISTS "isSpecialExpense" BOOLEAN NOT NULL DEFAULT false;
