services:
  - type: web
    name: octave-backend
    runtime: node
    plan: free # or starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: Test_Key_ID
        sync: false
      - key: Test_Key_Secret
        sync: false
    healthCheckPath: /health
    regions:
      - oregon
